### ISSUE TITLE
Patch not work on my omen

### ISSUE THREAD

**Issue by zlfn** [j0hnwang/OMEN-Transcend-16-ACPI-fix#1]
### Environment
**system** : OMEN by HP Transcend Gaming Laptop 16-u0xxx
**BIOS** : F.12 (or F.12.RevA? I recently updated it [here](https://support.hp.com/kr-ko/drivers/omen-by-hp-transcend-16-inch-gaming-laptop-pc-16-u0000/2101527111))
**distro**: CachyOS x86_64 (distro based on Arch Linux)
**kernel** : 6.7.4.2-cachyos
**DE** : Hyprland (Wayland)
**CPU** : 13th Gen Intel i7-13700HX
**GPU** : NVIDIA GeForce RTX 4070 Max-Q

I applied your fix as written. but linux didn't boot the same way with boot with out `noapic` kernel parameter.
I don't know what is problem. maybe... I need fix for F.12 RevA or something else.

**Comment by zlfn** [comment]
Here is BIOS screen shot
![20240211_012012.jpg](https://github.com/j0hnwang/OMEN-Transcend-16-ACPI-fix/assets/33383685/cbecaa84-33ec-455f-9647-d47a475fb6f0)

**Comment by zlfn** [comment]
Stucked at this point
![20240211_022823.jpg](https://github.com/j0hnwang/OMEN-Transcend-16-ACPI-fix/assets/33383685/7e034604-cdf2-428a-b95f-2f2aa32d77e8)

**Comment by zlfn** [comment]
I fixed the grub config but stucked at other point

![20240211_203108.jpg](https://github.com/j0hnwang/OMEN-Transcend-16-ACPI-fix/assets/33383685/67f92e9a-336a-4024-b8db-9498659e1e85)

![20240211_203117.jpg](https://github.com/j0hnwang/OMEN-Transcend-16-ACPI-fix/assets/33383685/d0c59307-449c-4a72-84a2-4e00b0528a90)

**Comment by zlfn** [comment]
I fixed the grub config but stucked at other point

![20240211_203108.jpg](https://github.com/j0hnwang/OMEN-Transcend-16-ACPI-fix/assets/33383685/67f92e9a-336a-4024-b8db-9498659e1e85)

![20240211_203117.jpg](https://github.com/j0hnwang/OMEN-Transcend-16-ACPI-fix/assets/33383685/d0c59307-449c-4a72-84a2-4e00b0528a90)

**Comment by zlfn** [comment]
I changed graphic option `dedicated` to `Advanced Optimus` and my omen printed different error.

Failed to mount on real root.
![20240211_214259.jpg](https://github.com/j0hnwang/OMEN-Transcend-16-ACPI-fix/assets/33383685/50ddff4f-4711-425e-99c0-8b5b098b9329)

**Comment by avncalst** [comment]
have the same pc and the same issue: patch not working

**Comment by avncalst** [comment]
I have a HP OMEN 16 laptop running ubuntu 22.04 with a 6.5.0-1014-oem kernel. I updated the  bios to version F.12 revA. To boot the laptop I still have to use noapic. I tried your patch F12 patch but I got a lot of errors during booting. I compared your dsdt.dsl (F.12) with the one of dsdt.dsl (F.12 revA) and they look very similar except the operation regions of SANV, GNVS, OGNS, MDBG and PNVB. There is also an extra device in the revA; Device (IC04). But with F.12 revA boot freezes after the touchpad (see photo).
Any advise? Thanks in advance for looking at my problem.
![IMG_3355_resized](https://github.com/j0hnwang/OMEN-Transcend-16-ACPI-fix/assets/13418617/23810d1f-2e84-4839-ad38-4e5a379f5eff)

**Comment by j0hnwang** [comment]
> I have a HP OMEN 16 laptop running ubuntu 22.04 with a 6.5.0-1014-oem kernel. I updated the bios to version F.12 revA. To boot the laptop I still have to use noapic. I tried your patch F12 patch but I got a lot of errors during booting. I compared your dsdt.dsl (F.12) with the one of dsdt.dsl (F.12 revA) and they look very similar except the operation regions of SANV, GNVS, OGNS, MDBG and PNVB. There is also an extra device in the revA; Device (IC04). But with F.12 revA boot freezes after the touchpad (see photo). Any advise? Thanks in advance for looking at my problem. ![IMG_3355_resized](https://private-user-images.githubusercontent.com/13418617/308659894-23810d1f-2e84-4839-ad38-4e5a379f5eff.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMDIzMTAsIm5iZiI6MTcwOTIwMjAxMCwicGF0aCI6Ii8xMzQxODYxNy8zMDg2NTk4OTQtMjM4MTBkMWYtMmU4NC00ODM5LWFkMzgtNGU1YTM3OWY1ZWZmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDEwMjAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlNzlhN2JkYzhjZmUwMDk1NmI3YTcwYzFjMzFjMGQwMjFiYjc3YWVhOTZlY2JhYzhkYTczYjE0OGU1Y2VhN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AAn118A7w91wTWbWk6t3WnB2H43QPhSvyXP76chN6T0)

Check commit 503346a2, you can see I removed IC04 from dsdt. System hang is caused by this buggy config when it's being interpreted by kernel. You can patch up your dsdt using commit 503346a2 and see what happens. 

I am not sure if HP is using same firmware throughout different countries. I got following version info from dmidecode.

BIOS Information
	Vendor: Insyde
	Version: F.12
	Release Date: 10/20/2023
	Address: 0xE0000
	Runtime Size: 128 kB
	ROM Size: 9728 kB
	Characteristics:
		PCI is supported
		BIOS is upgradeable
		BIOS shadowing is allowed
		Boot from CD is supported
		Selectable boot is supported
		EDD is supported
		Japanese floppy for NEC 9800 1.2 MB is supported (int 13h)
		Japanese floppy for Toshiba 1.2 MB is supported (int 13h)
		5.25"/360 kB floppy services are supported (int 13h)
		5.25"/1.2 MB floppy services are supported (int 13h)
		3.5"/720 kB floppy services are supported (int 13h)
		3.5"/2.88 MB floppy services are supported (int 13h)
		8042 keyboard services are supported (int 9h)
		CGA/mono video services are supported (int 10h)
		ACPI is supported
		USB legacy is supported
		BIOS boot specification is supported
		Targeted content distribution is supported
		UEFI is supported
	BIOS Revision: 15.12
	Firmware Revision: 64.37

**Comment by avncalst** [comment]
Thank you very much. It works!!!
